[package]
name = "rust-app"
version = "0.1.0"
edition = "2021"
authors = ["wkennedy"]

[dependencies]
warp = "0.3.5"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
tokio = { version = "1.30.0", features = ["rt-multi-thread", "macros"] }
bytes = "1.4.0"